# permissions for end users to edit records.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: record-editor-role
rules:
- apiGroups:
  - dns.cloudflare.k8s.kfirs.com
  resources:
  - records
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.cloudflare.k8s.kfirs.com
  resources:
  - records/status
  verbs:
  - get
