
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cloudflare-operator-role
rules:
- apiGroups:
  - cloudflare-operator.k8s.kfirs.com
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare-operator.k8s.kfirs.com
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare-operator.k8s.kfirs.com
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - get
  - list
