name: Build
on:
  push:
    branches: [ '**' ]
concurrency:
  group: ${{ github.ref }}
env:
  IMAGE: europe-docker.pkg.dev/arikkfir/public/cloudflare-operator
jobs:
  build:
    runs-on: self-hosted
    env:
      GOPATH: ${{ github.workspace }}/.gopath
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: ${GOPATH}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('go.mod') }}
      - uses: actions/checkout@v2
      - run: make test
      - run: docker build -t ${IMAGE}:${GITHUB_SHA} .
      - run: docker push ${IMAGE}:${GITHUB_SHA}
  tag-latest:
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: docker pull ${IMAGE}:${GITHUB_SHA}
      - run: docker tag ${IMAGE}:${GITHUB_SHA} ${IMAGE}:latest
      - run: docker push ${IMAGE}:latest
