name: Build
on:
  push:
    branches: [ '**' ]
concurrency:
  group: ${{ github.ref }}
env:
  IMAGE: europe-docker.pkg.dev/arikkfir/public/cloudflare-operator
jobs:
  build:
    runs-on: self-hosted
    env:
      GOPATH: ${{ github.workspace }}/.gopath
    steps:
      - run: chmod -R u+w .

      # CHECKOUT
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # CACHE
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      # TEST & BUILD
      - run: make test
      - run: docker build -t ${IMAGE}:${GITHUB_SHA} .
      - run: docker push ${IMAGE}:${GITHUB_SHA}
  tag-latest:
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: docker pull ${IMAGE}:${GITHUB_SHA}
      - run: docker tag ${IMAGE}:${GITHUB_SHA} ${IMAGE}:latest
      - run: docker push ${IMAGE}:latest
